"""Initial schema

Revision ID: 87a16f9bdf61
Revises: 
Create Date: 2025-12-09 00:09:14

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a16f9bdf61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_index('ix_coins_symbol', 'coins', ['symbol'], unique=False)
    op.create_index('ix_coins_symbol_last_updated', 'coins', ['symbol', 'last_updated'], unique=False)
    op.create_table('etl_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_cursor', sa.String(length=200), nullable=True),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('etl_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_etl_runs_run_id', 'etl_runs', ['run_id'], unique=False)
    op.create_index('ix_etl_runs_source', 'etl_runs', ['source'], unique=False)
    op.create_index('ix_etl_runs_source_started_at', 'etl_runs', ['source', 'started_at'], unique=False)
    op.create_table('raw_coin_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_coin_data_source', 'raw_coin_data', ['source'], unique=False)
    op.create_index('ix_raw_coin_data_source_external_id', 'raw_coin_data', ['source', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_coin_data_source_external_id', table_name='raw_coin_data')
    op.drop_index('ix_raw_coin_data_source', table_name='raw_coin_data')
    op.drop_table('raw_coin_data')
    op.drop_index('ix_etl_runs_source_started_at', table_name='etl_runs')
    op.drop_index('ix_etl_runs_source', table_name='etl_runs')
    op.drop_index('ix_etl_runs_run_id', table_name='etl_runs')
    op.drop_table('etl_runs')
    op.drop_table('etl_checkpoints')
    op.drop_index('ix_coins_symbol_last_updated', table_name='coins')
    op.drop_index('ix_coins_symbol', table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
